name: test

permissions:
  security-events: write
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: |
          echo "{}"

      # Runs a set of commands using the runners shell
      - name: upload sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json
          wait-for-processing: true
